packages:
  - 'artifacts/*'
  - 'lib/*'

catalog:
  "@tailwindcss/vite": "^4.1.4"
  "@tanstack/react-query": "^5.74.3"
  "@types/node": "^22.14.1"
  "@types/react": "^19.1.2"
  "@types/react-dom": "^19.1.2"
  "@vitejs/plugin-react": "^4.4.1"
  "@replit/vite-plugin-cartographer": "^0.5.1"
  "@replit/vite-plugin-dev-banner": "^0.1.0"
  "@replit/vite-plugin-runtime-error-modal": "^0.0.3"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "framer-motion": "^12.7.3"
  "lucide-react": "^0.488.0"
  "react": "^19.1.0"
  "react-dom": "^19.1.0"
  "tailwind-merge": "^2.6.0"
  "tailwindcss": "^4.1.4"
  "tw-animate-css": "^1.2.9"
  "vite": "^6.3.2"
  "wouter": "^3.3.5"
  "zod": "^3.24.2"
